<?php

/**
 * File: Validates repository structure, source headers, local links, action pins, and sensitive text.
 * Symbols: file discovery, header/link/action checks, symbol indexing, and report comparison.
 * State: validation issue list, source paths, symbol locations, and generated code-index content.
 */

declare(strict_types=1);

$root = dirname(__DIR__);
$checkOnly = in_array('--check', $argv, true);
$issues = [];
$required = [
    'README.md', 'LICENSE', 'SECURITY.md', 'CONTRIBUTING.md', 'Dockerfile', 'compose.yaml',
    'docs/architecture.md', 'docs/api.md', 'docs/complexity.md', 'docs/data-model.md',
    'docs/operations.md', 'docs/research.md', 'docs/security.md', 'docs/testing.md',
    'docs/reports/security-validation.md', 'docs/reports/test-results.md',
    'docs/reports/validation-results.md', 'docs/openapi.yaml',
];

foreach ($required as $path) {
    if (! is_file("{$root}/{$path}")) {
        $issues[] = "Missing required file: {$path}";
    }
}

$sourceRoots = ['app', 'database/factories', 'database/migrations', 'database/seeders', 'routes', 'resources/js', 'resources/css', 'resources/views', 'tests'];
$sources = ['bootstrap/app.php', 'vite.config.js', 'tools/validate_repo.php', 'scripts/verify.sh'];
foreach ($sourceRoots as $directory) {
    $absolute = "{$root}/{$directory}";
    if (! is_dir($absolute)) {
        continue;
    }
    $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($absolute, FilesystemIterator::SKIP_DOTS));
    foreach ($iterator as $file) {
        if ($file->isFile() && preg_match('/\.(php|js|css)$/', $file->getFilename())) {
            $sources[] = str_replace('\\', '/', substr($file->getPathname(), strlen($root) + 1));
        }
    }
}
$sources = array_values(array_unique($sources));
sort($sources);

foreach ($sources as $path) {
    $content = @file_get_contents("{$root}/{$path}");
    if ($content === false) {
        $issues[] = "Unreadable source file: {$path}";

        continue;
    }
    $header = implode("\n", array_slice(preg_split('/\R/', $content) ?: [], 0, 12));
    if (! str_contains($header, 'File:') || ! str_contains($header, 'State:')) {
        $issues[] = "Source header is incomplete: {$path}";
    }
    if (! preg_match('/(Symbols|Functions|Sections):/', $header)) {
        $issues[] = "Source header lacks a symbol summary: {$path}";
    }
}

$authoredFiles = [];
$tree = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS));
foreach ($tree as $file) {
    $relative = str_replace('\\', '/', substr($file->getPathname(), strlen($root) + 1));
    if (! $file->isFile() || preg_match('#^(vendor|node_modules|storage|public/build|\.git)/#', $relative)) {
        continue;
    }
    if (preg_match('/\.(php|js|css|md|ya?ml|json|sh)$/', $relative) || in_array($relative, ['Dockerfile', 'LICENSE'], true)) {
        $authoredFiles[$relative] = $file->getPathname();
    }
}

$forbidden = chr(79).chr(112).chr(116).chr(111).' '.chr(50).chr(50);
foreach ($authoredFiles as $relative => $absolute) {
    $content = file_get_contents($absolute);
    if (preg_match('/(?:AKIA[0-9A-Z]{16}|gh[pousr]_[A-Za-z0-9]{20,}|-----BEGIN (?:RSA |EC )?PRIVATE KEY-----)/', $content)) {
        $issues[] = "Possible credential material in {$relative}";
    }
    if (stripos($content, $forbidden) !== false) {
        $issues[] = "Forbidden employer reference in {$relative}";
    }
}

$docs = array_filter($authoredFiles, fn ($path) => $path === 'README.md' || str_starts_with($path, 'docs/'), ARRAY_FILTER_USE_KEY);
foreach ($docs as $doc) {
    $content = file_get_contents($doc);
    preg_match_all('/\[[^\]]+\]\((?!https?:\/\/|mailto:|#)([^)#]+)(?:#[^)]+)?\)/', $content, $matches);
    foreach ($matches[1] as $target) {
        $decoded = rawurldecode($target);
        $resolved = realpath(dirname($doc).DIRECTORY_SEPARATOR.$decoded);
        if ($resolved === false) {
            $issues[] = 'Broken local link in '.basename($doc).": {$target}";
        }
    }
}

foreach (glob("{$root}/.github/workflows/*.yml") ?: [] as $workflow) {
    $content = file_get_contents($workflow);
    preg_match_all('/uses:\s+[^@\s]+@([^\s#]+)/', $content, $matches);
    foreach ($matches[1] as $reference) {
        if (! preg_match('/^[a-f0-9]{40}$/', $reference)) {
            $issues[] = 'Action is not pinned to a full commit in '.basename($workflow).": {$reference}";
        }
    }
}

$index = [
    '# Code index',
    '',
    'Generated by `php tools/validate_repo.php`. Line numbers refer to the committed source revision.',
    '',
];
foreach ($sources as $path) {
    $lines = preg_split('/\R/', (string) file_get_contents("{$root}/{$path}")) ?: [];
    $symbols = [];
    $variables = [];
    foreach ($lines as $offset => $line) {
        $lineNumber = $offset + 1;
        if (preg_match_all('/\b(?:class|enum|interface|trait|function)\s+([A-Za-z_]\w*)|\bconst\s+([A-Za-z_]\w*)/', $line, $found, PREG_SET_ORDER)) {
            foreach ($found as $match) {
                $symbols[$match[1] !== '' ? $match[1] : $match[2]][] = $lineNumber;
            }
        }
        if (preg_match_all('/(?<![A-Za-z0-9_])(\$[A-Za-z_]\w*)/', $line, $found)) {
            foreach ($found[1] as $name) {
                $variables[$name][] = $lineNumber;
            }
        }
        if (preg_match_all('/\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)/', $line, $found)) {
            foreach ($found[1] as $name) {
                $variables[$name][] = $lineNumber;
            }
        }
        if (preg_match_all('/(--[a-z0-9-]+)\s*:/i', $line, $found)) {
            foreach ($found[1] as $name) {
                $variables[$name][] = $lineNumber;
            }
        }
    }
    $index[] = "## `{$path}`";
    $index[] = '';
    $index[] = '**Symbols:** '.($symbols === [] ? 'No named declarations.' : implode('; ', array_map(
        fn ($name, $locations) => "`{$name}` (lines ".implode(', ', array_unique($locations)).')',
        array_keys($symbols),
        array_values($symbols),
    )));
    $index[] = '';
    $index[] = '**Variables/state:** '.($variables === [] ? 'No named variables.' : implode('; ', array_map(
        fn ($name, $locations) => "`{$name}` (lines ".implode(', ', array_unique($locations)).')',
        array_keys($variables),
        array_values($variables),
    )));
    $index[] = '';
}
$generated = implode("\n", $index)."\n";
$indexPath = "{$root}/docs/code-index.md";
if ($checkOnly) {
    if (! is_file($indexPath) || file_get_contents($indexPath) !== $generated) {
        $issues[] = 'docs/code-index.md is missing or stale; regenerate it before committing.';
    }
} else {
    if (! is_dir(dirname($indexPath))) {
        mkdir(dirname($indexPath), 0777, true);
    }
    file_put_contents($indexPath, $generated);
}

if ($issues !== []) {
    foreach ($issues as $issue) {
        fwrite(STDERR, "[FAIL] {$issue}\n");
    }
    exit(1);
}

echo '[PASS] Repository validation completed for '.count($sources)." source files.\n";
